name: Generate SECURITY.md

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
  # Also runs if the template file is ever changed on the main branch
  push:
    branches:
      - main
      - master
    paths:
      - 'SECURITY.md.template'

permissions:
  # This permission is required to commit the generated file back to the repo
  contents: write

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Substitute Placeholders
        run: |
          # Use the repository name for the project name (e.g., "repo-again" -> "Repo Again")
          PROJECT_NAME=$(echo "${{ github.event.repository.name }}" | sed 's/-/ /g' | sed -E 's/\b(.)/\u\1/g')
          OWNER_NAME="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          CONTACT_EMAIL="${{ secrets.SECURITY_CONTACT_EMAIL }}"

          # Create a copy of the template to work with
          cp SECURITY.md.template SECURITY.md

          # Perform the substitutions
          sed -i "s/__PROJECT_NAME__/$PROJECT_NAME/g" SECURITY.md
          sed -i "s/__OWNER__/$OWNER_NAME/g" SECURITY.md
          sed -i "s/__REPO__/$REPO_NAME/g" SECURITY.md
          sed -i "s/__SECURITY_CONTACT_EMAIL__/$CONTACT_EMAIL/g" SECURITY.md

      - name: Commit generated SECURITY.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(security): generate SECURITY.md from template"
          file_pattern: "SECURITY.md"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
